/**
 * Lego slot wiring + config — GENERATED by _legos_config_generator.py
 * at substrate install time. DO NOT hand-edit.
 *
 * Spec authority: NEXUS_PORTFOLIO_RUNTIME_SPEC.md §4.4.
 */

export interface LegoSlot {
  readonly name: string;
  readonly contract: string;
  readonly description?: string;
}

export interface LegoConfig {
  readonly name: string;
  readonly version: string;
  readonly isStub: boolean;
  readonly slots: readonly LegoSlot[];
  readonly config: Record<string, unknown>;
}

export const LEGOS: readonly LegoConfig[] = [
  {
    "config": {
      "properties": {
        "default_permissions": {
          "description": "Roles that have access to the admin console by default.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "enable_feature_flags": {
          "default": true,
          "description": "Enable the feature flags admin section.",
          "type": "boolean"
        },
        "enable_impersonation": {
          "default": false,
          "description": "Show impersonation button in admin shell. Actual session-switching is deferred to a future security-review sprint.\n",
          "type": "boolean"
        }
      },
      "required": [
        "default_permissions",
        "enable_impersonation",
        "enable_feature_flags"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "admin-console",
    "slots": [
      {
        "contract": "react-component",
        "description": "Extra navigation items injected into the admin sidebar by other legos.",
        "name": "admin_nav_extra"
      },
      {
        "contract": "react-component",
        "description": "Widgets contributed to the admin dashboard overview page.",
        "name": "admin_dashboard_widgets"
      },
      {
        "contract": "react-component",
        "description": "Per-row action buttons injected into the admin users table (e.g. Identity & Access \"force delete\" / \"revoke sessions\").",
        "name": "admin_user_actions"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "analytics-and-telemetry",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "properties": {
        "default_currency": {
          "description": "Default currency for new subscriptions.",
          "enum": [
            "usd",
            "eur",
            "gbp",
            "cad",
            "aud"
          ],
          "type": "string"
        },
        "enable_proration": {
          "default": true,
          "type": "boolean"
        },
        "stripe_publishable_key": {
          "description": "Stripe publishable key (pk_live_... or pk_test_...). Secret key is read from env STRIPE_SECRET_KEY.",
          "type": "string"
        },
        "tier_ladder": {
          "description": "Pricing tiers exposed in checkout. Maps to chairman's $14/$24/$59/$99 ladder by default.",
          "items": {
            "properties": {
              "amount": {
                "description": "Cents",
                "type": "integer"
              },
              "interval": {
                "enum": [
                  "month",
                  "year"
                ],
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "price_id": {
                "description": "Stripe Price ID (price_...)",
                "type": "string"
              }
            },
            "required": [
              "name",
              "price_id",
              "amount",
              "interval"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "trial_days": {
          "default": 0,
          "maximum": 90,
          "minimum": 0,
          "type": "integer"
        }
      },
      "required": [
        "stripe_publishable_key",
        "default_currency",
        "tier_ladder"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "billing-and-subscriptions",
    "slots": [
      {
        "contract": "react-component",
        "description": "Extra form fields injected into the checkout flow (e.g., promo code, referral source).",
        "name": "checkout_extra_fields"
      },
      {
        "contract": "server-hook",
        "description": "Server-side hook to redirect after successful subscription creation.",
        "name": "post_subscription_redirect"
      },
      {
        "contract": "react-component",
        "description": "Per-subscription metadata fields appended to the Stripe subscription record.",
        "name": "subscription_extra_metadata"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "crm-and-lifecycle",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "developer-surface",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "files-and-media",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "properties": {
        "mfa": {
          "description": "MFA configuration (wired in 2.2)",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "enforcement": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "password_policy": {
          "description": "Password strength requirements",
          "properties": {
            "min_length": {
              "type": "integer"
            },
            "require_digit": {
              "type": "boolean"
            },
            "require_special": {
              "type": "boolean"
            },
            "require_uppercase": {
              "type": "boolean"
            }
          },
          "type": "object"
        },
        "providers": {
          "description": "Authentication providers to enable",
          "items": {
            "enum": [
              "email",
              "google_oauth",
              "github_oauth",
              "passkey",
              "totp"
            ],
            "type": "string"
          },
          "type": "array"
        }
      },
      "required": [
        "providers",
        "password_policy"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "identity-and-access",
    "slots": [
      {
        "contract": "react-component",
        "description": "Inject custom fields or UI elements above the standard email/password inputs on the signup form.\n",
        "name": "before_signup_fields"
      },
      {
        "contract": "react-component",
        "description": "Legal acknowledgment block shown at the bottom of the signup form. Defaults to a standard ToS + privacy placeholder; full email-linked template lands in 2.2.\n",
        "name": "signup_legal_acknowledgment"
      },
      {
        "contract": "server-hook",
        "description": "Server hook executed after a successful login to determine where to redirect the user. Falls back to /dashboard when not configured.\n",
        "name": "after_login_redirect"
      }
    ],
    "version": "1.0.0"
  },
  {
    "config": {
      "properties": {
        "cookie_banner_enabled": {
          "default": true,
          "description": "Show cookie consent banner to new visitors.",
          "type": "boolean"
        },
        "jurisdiction": {
          "default": "us",
          "description": "Primary legal jurisdiction for this company's documents.",
          "enum": [
            "us",
            "eu",
            "uk",
            "ca",
            "au",
            "global"
          ],
          "type": "string"
        },
        "liability_boundary_class": {
          "default": "assistant",
          "description": "Mirrors spec \u00a78. Controls strictness of disclosure flows. regulated_advisor and fiduciary companies get additional disclosure requirements wired into every external communication.\n",
          "enum": [
            "tool",
            "assistant",
            "fiduciary",
            "regulated_advisor"
          ],
          "type": "string"
        }
      },
      "required": [
        "jurisdiction",
        "cookie_banner_enabled",
        "liability_boundary_class"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "legal-and-compliance",
    "slots": [
      {
        "contract": "react-component",
        "description": "Additional links injected into the site footer alongside the standard Terms / Privacy / Cookie Policy links. Other legos may inject their own compliance links here (e.g. sub-processor list, DPA download).\n",
        "name": "extra_legal_links"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Terms of Service document. Use for company-specific clauses that cannot go in the base template.\n",
        "name": "policy_addendum_terms_of_service"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Privacy Policy document.\n",
        "name": "policy_addendum_privacy_policy"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Cookie Policy document.\n",
        "name": "policy_addendum_cookie_policy"
      },
      {
        "contract": "server-hook",
        "description": "Addendum injected at the end of the Accessibility Statement document.\n",
        "name": "policy_addendum_accessibility_statement"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "properties": {
        "contradiction_threshold": {
          "default": 3,
          "description": "Contradicting newer observations before a long-term memory is demoted.",
          "maximum": 10,
          "minimum": 1,
          "type": "integer"
        },
        "knowledge_compiler_debounce_seconds": {
          "default": 300,
          "description": "Min seconds between compiler runs per company.",
          "maximum": 3600,
          "minimum": 30,
          "type": "integer"
        },
        "long_term_eviction_no_retrieval_days": {
          "default": 90,
          "description": "Long-term entries flagged low-value if not retrieved in N days.",
          "maximum": 365,
          "minimum": 30,
          "type": "integer"
        },
        "working_memory_ttl_days": {
          "default": 7,
          "description": "Working-tier memories evicted after N idle days (spec \u00a75.6).",
          "maximum": 90,
          "minimum": 1,
          "type": "integer"
        }
      },
      "required": [
        "working_memory_ttl_days",
        "long_term_eviction_no_retrieval_days"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "memory-and-knowledge",
    "slots": [
      {
        "contract": "react-component",
        "description": "Admin-console pane showing per-company memory rows + tier badges",
        "name": "admin_memory_inspector"
      },
      {
        "contract": "react-component",
        "description": "User-facing GDPR export + forget-me controls",
        "name": "user_memory_export"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "properties": {
        "default_channels": {
          "description": "Channels enabled by default for new users. User can opt out per-channel via /api/notifications/preferences.",
          "items": {
            "enum": [
              "email",
              "in_app",
              "web_push",
              "sms"
            ],
            "type": "string"
          },
          "type": "array"
        },
        "rate_limit_per_user_per_hour": {
          "default": 30,
          "maximum": 1000,
          "minimum": 1,
          "type": "integer"
        },
        "resend_from_email": {
          "description": "Verified sender address for Resend (e.g. notifications@example.com).",
          "type": "string"
        },
        "twilio_messaging_service_sid": {
          "description": "Optional Twilio Messaging Service SID. Required only if 'sms' is in default_channels.",
          "type": "string"
        },
        "web_push_vapid_public_key": {
          "description": "Optional VAPID public key for web push. Required only if 'web_push' in default_channels.",
          "type": "string"
        }
      },
      "required": [
        "resend_from_email",
        "default_channels"
      ],
      "type": "object"
    },
    "isStub": false,
    "name": "notifications",
    "slots": [
      {
        "contract": "react-component",
        "description": "HTML injected at the top of every transactional email (logo, brand banner).",
        "name": "email_layout_header"
      },
      {
        "contract": "react-component",
        "description": "HTML injected at the bottom of every transactional email (legal footer, unsubscribe link).",
        "name": "email_layout_footer"
      },
      {
        "contract": "react-component",
        "description": "Per-row action buttons injected into the in-app inbox.",
        "name": "in_app_inbox_extra_actions"
      }
    ],
    "version": "0.1.0"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "onboarding",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "organizations-and-teams",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "profile-and-account",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "search",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "social-and-engagement",
    "slots": [],
    "version": "0.0.0-stub"
  },
  {
    "config": {
      "additionalProperties": true,
      "properties": {},
      "type": "object"
    },
    "isStub": true,
    "name": "support-and-help",
    "slots": [],
    "version": "0.0.0-stub"
  }
];

export function findSlotProvider(slotName: string): LegoConfig | undefined {
  return LEGOS.find((lego) =>
    lego.slots.some((slot) => slot.name === slotName),
  );
}
